#pragma once
enum SCENE { SCENE_LOGO, SCENE_STAGE, SCENE_OVER, SCENE_END };
enum DIR { DIR_DOWN, DIR_UP, DIR_LEFT, DIR_RIGHT, DIR_END };
enum TYPE { TYPE_PLAYER, TYPE_WIZARD, TYPE_BOSS, TYPE_SWORD, TYPE_SWORD_ATTACK, TYPE_ARCHER, TYPE_END };
enum TIMER {};